### ISSUE TITLE
Django Tenants

### ISSUE THREAD

**Issue by tomturner** [Corvia/django-tenant-users#1]
This project will work will also work on https://github.com/tomturner/django-tenants it was a clone of django-tenant-schemas when a group of us though it was a dead project.
It now has some enhancements like parallel migrations which django-tenant-schemas doesn't have (as far I know)

Any chance you could mention django-tenants version as well?
 I will put a link back to you as well

Keep up the good work

**Comment by Viatrak** [comment]
I added a compatibility layer in commit 7b0e9c4 that should support both django-tenants or django-tenants-schema and updated docs in 8417f00.
