### ISSUE TITLE
Admin site login per Tenant and changing User permissions

### ISSUE THREAD

**Issue by mauroeparis** [Corvia/django-tenant-users#13]
When trying to log in at tenants Admin page (Except Public's Admin) no user that I create gets to do it. I created 3 users by now in these different ways:

```python
eviluser = TenantUser.objects.create_user(email="evil@corp.com", password='password', is_active=True)
staffuser = TenantUser.objects.create_user(email="staff@user.com", password='password', is_staff=True, is_active=True)
```
and the third one using ```manage.py createsuperuser``` on the public schema (I'm unable to create a superuser in a schema that isn't public), I will refer to it as surperuser.

```staffuser``` and ```superuser``` can login into the public tenant admin page but when trying to log into other tenants admin page I get this message:

![imagen](https://user-images.githubusercontent.com/13922772/35810857-ce53e75a-0a6b-11e8-8fa3-7fb94309de89.png)

I get an expected follow up error if i try with the same credentials saying "Please enter the correct Email Address and password for a staff account. Note that both fields may be case-sensitive."

Using ```python manage.py shell``` I have added both of these users to both tenats using the ```tenantObject.add_user(staffuser/superuser)```, in addition I have made staffuser the owner of the second tenant using ```superuser``` in the public tenant admin page but I still can't get any of the users to log into this tenant.

I have checked if they have been correctly added to the tenant,  using the function ```tenant1.user_set.all()``` and it shows both users.

```eviluser``` can't login into any admin page and I understand that this is because it has no staff permissions.

My question is how do I grant ```superuser``` and ```staffuser``` the permissions needed to login into other tenants admin site and also how can I change permissions once inside the admin site? (i.e. allowing ```staffuser``` to edit information in public tenant admin site or granting superuser all permissions in all tenant admin sites)

Here is my ```settings.py``` on this [gist](https://gist.github.com/bonzomontreus/68964ca7885d570e2c4b63293b7a8370) , I'm using django-tenant-users along with [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas).

**Comment by ivissani** [comment]
Did you create the UserTenantPermissions object for that user in the corresponding tenant?
I've found that you need to do something in the line of

```python
user = user_model.objects.create_user(email=user_email, password=None, is_staff=True)

tenants = tenant_model.objects.all()
for tenant in tenants:
    with tenant_context(tenant):
         perm = UserTenantPermissions.objects.get_or_create(profile=user, is_staff=True)
```

In this case we are setting the property `is_staff` for the user in every tenant. Your needs may be different.

**Comment by bonzomontreus** [comment]
That does solve the login for both tenants. However, the `superuser` cannot read or edit anything at the second tenant admin site and `staffuser` cannot do it in any tenant.

![imagen](https://user-images.githubusercontent.com/13922772/35861633-55ff0dfe-0b27-11e8-8443-982880728264.png)

This is all I get to see in the second tenant and it's the same with any user I get to login, even new users. 
How should I grant read/write permission to users on specific tenants? Can I mirror permissions of an user in another Tenant?

**Comment by bonzomontreus** [comment]
In addition, can I create users that are staff of certain tenants but cannot login to the public tenant admin page? and if so, how do i manage to create said user?

**Comment by ivissani** [comment]
I'm not quite sure of what's going on. superusers _are granted_ all the permissions by default you can check `has_perm` implementation in the class `PermissionsMixin`, in particular lines 272-274 state the following:

```python
        # Active superusers have all permissions.
        if self.is_active and self.is_superuser:
            return True
```

So superusers get all permissions no matter whether you granted them or not.

**Comment by ivissani** [comment]
With regards to having users that are staff on certain tenants but not on the public tenant, setting the `is_staff` and `is_superuser` properties to `False` in the `UserTenantPermission` object corresponding to that user in the public tenant should do the trick. I did not test this but it should work.

**Comment by bonzomontreus** [comment]
So superusers should have all permissions in all tenants where it can get logged in?

**Comment by ivissani** [comment]
As long as you set the `is_superuser` property for that user on each tenant.

**Comment by eamtalu** [comment]
> When trying to log in at tenants Admin page (Except Public's Admin) no user that I create gets to do it. I created 3 users by now in these different ways:
> 
> ```python
> eviluser = TenantUser.objects.create_user(email="evil@corp.com", password='password', is_active=True)
> staffuser = TenantUser.objects.create_user(email="staff@user.com", password='password', is_staff=True, is_active=True)
> ```
> 
> and the third one using `manage.py createsuperuser` on the public schema (I'm unable to create a superuser in a schema that isn't public), I will refer to it as surperuser.
> 
> `staffuser` and `superuser` can login into the public tenant admin page but when trying to log into other tenants admin page I get this message:
> 
> ![imagen](https://user-images.githubusercontent.com/13922772/35810857-ce53e75a-0a6b-11e8-8fa3-7fb94309de89.png)
> 
> I get an expected follow up error if i try with the same credentials saying "Please enter the correct Email Address and password for a staff account. Note that both fields may be case-sensitive."
> 
> Using `python manage.py shell` I have added both of these users to both tenats using the `tenantObject.add_user(staffuser/superuser)`, in addition I have made staffuser the owner of the second tenant using `superuser` in the public tenant admin page but I still can't get any of the users to log into this tenant.
> 
> I have checked if they have been correctly added to the tenant, using the function `tenant1.user_set.all()` and it shows both users.
> 
> `eviluser` can't login into any admin page and I understand that this is because it has no staff permissions.
> 
> My question is how do I grant `superuser` and `staffuser` the permissions needed to login into other tenants admin site and also how can I change permissions once inside the admin site? (i.e. allowing `staffuser` to edit information in public tenant admin site or granting superuser all permissions in all tenant admin sites)
> 
> Here is my `settings.py` on this [gist](https://gist.github.com/bonzomontreus/68964ca7885d570e2c4b63293b7a8370) , I'm using django-tenant-users along with [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas).

HI,

I am running the project in local machine and after setting up django-tenants and django-tenant-users, the admin page is not showing up, syaing page not found. urls.py is below:
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('^admin/', admin.site.urls),
]

I am trying to access it by: http://0.0.0.0:8000/admin

getting error:

=====
Request Method: | GET
-- | --
http://localhost:8000/

No tenant for hostname "localhost"
====

Is there anything specific I need to do in settings or URLs or anywhere ?

The help would be highly appreciated.

Thanks
Amin

@mauroeparis @Viatrak

**Comment by mauroeparis** [comment]
Hello!

Sorry for the delay! 

I do not have the code of the project that used this package anymore but I am pretty sure you need to create a `Tenant` instance that has the http://localhost:8000/ url

Hope this helps and happy coding
