### ISSUE TITLE
Log In Failed

### ISSUE THREAD

**Issue by Jromero97** [Corvia/django-tenant-users#15]
Hi, I register users to my tenant in public and extra tenant but doesn't matter I can't log in on the admin site... Some help here please.

**Comment by ajmatsick** [comment]
When you say you registered the user in the non-public tenants, do you mean you created a `UserTenantPermissions` instance in each tenant for the user, either via `TenantBase.add_user` or manually (e.g., as described [here](/Corvia/django-tenant-users/issues/13#issuecomment-363124391))? If so, is `is_staff` set to `True` where applicable?

**Comment by Jromero97** [comment]
All that is correct, I check the permissions, and both is staff an is superuser is active!

**Comment by RuchitMicro** [comment]
@Jromero97 Did you solved this?
