### ISSUE TITLE
Make compatible with Django 4.0

### ISSUE THREAD

**Issue by roordaj** [Corvia/django-tenant-users#158]
Hi,

I just started using DTU in a Django 4.0 project. I noticed that the following changes had to be made to be compatible. I made the changes in my virtualenv and it's working now, but it would be great if it is changed in the source code so that i dont have to ship my own copy of DTU with the source code. I'm relatively new to Django so please advice if there is a better way to solve these issues.

Following changes have to be made:
**tenants > models.py**
- replace ugettext_lazy with gettext_lazy
- remove providing_args from the Signals

**permissions > models.py**
- replace ugettext_lazy with gettext_lazy

**Comment by Dresdn** [comment]
I thought there was a Django 4.0 issue already, so thanks for opening. More than happy to take a look at a PR, otherwise, I'll add it and get a release out, which is way overdue.

**Comment by roordaj** [comment]
Thanks so much @Dresdn! When are you planning to create a new release and push that to PyPi?

**Comment by Dresdn** [comment]
Hi @roordaj - I'll get something out this week! I've been dragging my feet a bit on it.
