### ISSUE TITLE
BigAutoField migration

### ISSUE THREAD

**Issue by JupiterThreads** [Corvia/django-tenant-users#162]
I think from Django 3.2 all the id fields are now created as model.BigAutoField. When I do a fresh install of django-tenant-users, its always asking me to create a migration file to change the id field on the UserTenantPermissions model to the BigAutoField. Is this something that can be done before the next release? This is the migration file it keeps on creating for me that then gets added to the permission migrations folder. Thanks!

```
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertenantpermissions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]

```

**Comment by Dresdn** [comment]
I noticed this with the [django 4.0 work](#161 ), and I have an idea to prevent this for django 2.2, 3.2, and 4.0.

**Comment by Dresdn** [comment]
@JupiterThreads - Are you still seeing this in the latest `master`? I just setup a new project and went from Django 2.2 -> 3.2 -> 4.0 with `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'` and `makemigrations` didn't show any migrations.

**Comment by JupiterThreads** [comment]
Nope, seems to work. Thanks!
