### ISSUE TITLE
Accessing the Model that captures the user-tenants association

### ISSUE THREAD

**Issue by lukik** [Corvia/django-tenant-users#21]
I want to access the model capturing the list of Tenants a User has access to.  

Looking at the code, `UserProfile.tenants` is a ManyToMany entry and so the `UserTenants` model code is not accessible. To make it accessible, I've tried, overriding the `tenants` field in my `User` Model and added a `through=UserTenant` entry and created the relevant `UserTenant` model. 

    tenants = models.ManyToManyField(
        settings.TENANT_MODEL,
        verbose_name=_('tenants'),
        blank=True,
        help_text=_('The tenants this user belongs to.'),
        related_name="user_set",
        through='UserTenant',    <===========Added this to refer to the UserTenant model below
    )

```
class UserTenant(models.Model):
    """
    Tenants that the user has been added to
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True) 
```

However, this brings up new errors.

```
from tenant_users.tenants.utils import create_public_tenant
create_public_tenant("evil.corp", "admin@evil.corp")
```

This bring the error..

`AttributeError: Cannot use add() on a ManyToManyField which specifies an intermediary model. Use authentication.UserTenant's Manager instead.`

Or am I going at it the wrong way? Is there an easier way to access this model?

Am using [django-tenants](https://github.com/tomturner/django-tenants) with `Django Rest Framework` and building custom permissions for the API calls so I want to reference the model as below:

```
class UserTenantRole(models.Model):
    """
    Roles given to a user within a tenant
    """
    user_tenant = models.ForeignKey(UserTenant, on_delete=models.CASCADE)  <====Access it here
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
```

**Comment by Viatrak** [comment]
It should be straight forward to access all tenants that a user belongs to and perhaps exclude the public tenant as such:

user.tenants.all().exclude(id=public_tenant.id)
