### ISSUE TITLE
No permissions in Public Tenant's Django Admin 

### ISSUE THREAD

**Issue by daniel-butler** [Corvia/django-tenant-users#210]
Python: 3.9
Django: 3.2.12
Django-tenants: 3.4.2
Django-tenant-users: 1.0.0

I have an admin who I want to make an admin in all tenants including the public tenant.

<img width="615" alt="Screen Shot 2022-03-26 at 1 53 19 PM" src="https://user-images.githubusercontent.com/22578954/160251505-4174c80c-44c6-436d-9abb-61548a0554d6.png">

The user has all of the permissions in the public tenant

```py
from django_tenants.utils import tenant_context, get_tenant_model, get_public_schema_name
from project.users.models import User


public = get_tenant_model().objects.get(schema_name=get_public_schema_name())
admin = User.objects.get(email="admin@email.com")

with tenant_context(public):
    admin.tenant_perms.get_all_permissions()
```

Prints out

```py
{'socialaccount.view_socialaccount', 'address.delete_country', 'customers.view_domain', 'contenttypes.view_contenttype', 'customers.change_client', 'customers.delete_client', 'permissions.delete_usertenantpermissions', 'address.delete_state', 'socialaccount.add_socialapp', 'sessions.change_session', 'address.add_locality', 'address.change_address', 'account.delete_emailaddress', 'sessions.view_session', 'auth.change_permission', 'address.change_locality', 'account.view_emailconfirmation', 'users.change_user', 'authtoken.delete_tokenproxy', 'authtoken.add_tokenproxy', 'contenttypes.change_contenttype', 'permissions.add_usertenantpermissions', 'orders_tenant.add_line', 'address.change_state', 'orders_tenant.delete_header', 'address.view_locality', 'auth.add_group', 'authtoken.delete_token', 'orders_tenant.view_product', 'orders_tenant.view_listing', 'account.change_emailconfirmation', 'auth.delete_group', 'customers.change_domain', 'permissions.view_usertenantpermissions', 'users.add_user', 'address.view_country', 'socialaccount.view_socialtoken', 'auth.view_group', 'orders_tenant.change_product', 'auth.add_permission', 'address.add_address', 'account.add_emailconfirmation', 'socialaccount.delete_socialaccount', 'authtoken.add_token', 'socialaccount.change_socialapp', 'orders_tenant.change_listing', 'orders_tenant.delete_product', 'account.add_emailaddress', 'socialaccount.delete_socialtoken', 'address.view_address', 'account.change_emailaddress', 'orders_tenant.add_listing', 'authtoken.change_token', 'authtoken.change_tokenproxy', 'socialaccount.delete_socialapp', 'customers.add_domain', 'customers.view_client', 'address.add_country', 'address.delete_locality', 'orders_tenant.view_header', 'socialaccount.add_socialtoken', 'contenttypes.add_contenttype', 'account.delete_emailconfirmation', 'orders_tenant.change_header', 'users.delete_user', 'auth.change_group', 'sessions.add_session', 'admin.add_logentry', 'address.delete_address', 'auth.delete_permission', 'orders_tenant.add_product', 'contenttypes.delete_contenttype', 'orders_tenant.view_line', 'customers.add_client', 'account.view_emailaddress', 'socialaccount.change_socialaccount', 'admin.change_logentry', 'socialaccount.view_socialapp', 'address.change_country', 'sessions.delete_session', 'orders_tenant.change_line', 'orders_tenant.add_header', 'authtoken.view_tokenproxy', 'admin.delete_logentry', 'permissions.change_usertenantpermissions', 'address.add_state', 'auth.view_permission', 'socialaccount.add_socialaccount', 'address.view_state', 'customers.delete_domain', 'authtoken.view_token', 'orders_tenant.delete_line', 'socialaccount.change_socialtoken', 'users.view_user', 'orders_tenant.delete_listing', 'admin.view_logentry'}
```

In the public tenant's context if I check that the user has superuser and staff permissions they are both true.

```py
admin.is_superuser
admin.is_staff
```
Both are True.

Also, I added the admin to every tenant including the public tenant. I know that part is correct because I wouldn't be able to access the tenant_perms property if the user wasn't attached to the public tenant.

I tried logging out then logging back in, in the public tenant thinking it might be a cookie issue. Also, logging in from a private window each time I could log in but I get the permission error above.

settings.py
```py

DJANGO_SHARED_APPS = [
    "django_tenants",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # Handy template tags
    "django.forms",
]

THIRD_PARTY_SHARED_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "widget_tweaks",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    # Tenancy
    "tenant_users.permissions",
    "tenant_users.tenants",
    # Order Related
    "djmoney",
    "address",
]

LOCAL_SHARED_APPS = [
    "listing_service.frontpages",
    # Tenancy
    "listing_service.customers",
    "listing_service.users",
]

# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
SHARED_APPS = DJANGO_SHARED_APPS + THIRD_PARTY_SHARED_APPS + LOCAL_SHARED_APPS
```

**Comment by daniel-butler** [comment]
I was thinking it was related to not having any models or apps in the public/shared tenant. Because the apps are in the shared list, I don’t think that is the issue.

**Comment by Dresdn** [comment]
What are your `TENANT_APPS` and `INSTALLED_APPS` set to? Something seems odd in that if your user `is_superuser`, all permissions are enabled. This is unless you're using something like `django-guardian`, which it seems you're not.

**Comment by daniel-butler** [comment]
```py
# APPS
# ------------------------------------------------------------------------------
# SHARED
# ------------------------------------------------------------------------------
DJANGO_SHARED_APPS = [
    "django_tenants",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # Handy template tags
    "django.forms",
]

THIRD_PARTY_SHARED_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "widget_tweaks",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    # Tenancy
    "tenant_users.permissions",
    "tenant_users.tenants",
    # Order Related
    "djmoney",
    "address",
]

LOCAL_SHARED_APPS = [
    "listing_service.frontpages",
    # Tenancy
    "listing_service.customers",
    "listing_service.users",
]

# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
SHARED_APPS = DJANGO_SHARED_APPS + THIRD_PARTY_SHARED_APPS + LOCAL_SHARED_APPS

# TENANT SPECIFIC
# ------------------------------------------------------------------------------

DJANGO_TENANT_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
]

THIRD_PARTY_TENANT_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "widget_tweaks",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    # Tenancy
    "tenant_users.permissions",
]

LOCAL_TENANT_APPS = [
    "listing_service.orders_tenant",
    "listing_service.frontpages_tenant",
    "listing_service.clientportal_tenant",
]

TENANT_APPS = DJANGO_TENANT_APPS + THIRD_PARTY_TENANT_APPS + LOCAL_TENANT_APPS

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]
```

I follow the Django cookiecutter  method of breaking up the apps lists.

**Comment by Dresdn** [comment]
Starting with a side-note, you don't need to list the Third Part Apps that are pure utility apps, such as `crispy_forms`. Should make it easier to maintain and manage.

I'm wondering if this could be related to the AllAuth setup, but that's a pure hunch. What's interesting is that when you are in the Public Admin section, you should see a `TENANT_ONLY` section that says `Not available for global schema`. Since you don't, this is where I'm thinking the AllAuth authentication backend may not be set up correctly.

To be sure, when you login to /admin under a tenant as that user, you do see everything as expected?

**Comment by daniel-butler** [comment]
> Starting with a side-note, you don't need to list the Third Part Apps that are pure utility apps, such as `crispy_forms`. Should make it easier to maintain and manage.

Good to know! For my understanding, is it basically any app that doesn’t have a model/ db migration can be put directly into `INSTALLED_APPS`?


> I'm wondering if this could be related to the AllAuth setup, but that's a pure hunch. What's interesting is that when you are in the Public Admin section, you should see a `TENANT_ONLY` section that says `Not available for global schema`. Since you don't, this is where I'm thinking the AllAuth authentication backend may not be set up correctly.


 I didn’t know that there is a section that says only editable by tenant.  When I’m back at my computer I’ll see if I can find anything related to all south’s authentication and how I have it configure. 

> To be sure, when you login to /admin under a tenant as that user, you do see everything as expected?

yeah, this is what it looks like if I am in a tenant as the same user. 

![E1E4E1BD-64AF-4028-B515-0A93B72A3B47](https://user-images.githubusercontent.com/22578954/160311735-46c53998-6a06-41cc-aa1c-eda9a7bda9d2.jpeg)


When I created the public tenant I ran from the readme

**Comment by daniel-butler** [comment]
When I spun up a clean instance on my laptop, I was able to access the Django admin site after setting the user to superuser and staff in the public tenant. I must have set something up incorrectly. I didn't fully understand what I was doing back then, at least not as much as I get now. :)

**Comment by daniel-butler** [comment]
After looking at the values in the database I didn't have `is_superuser` set for the profile/user in the public schema. After giving them access by updating the `public.permissions_usertenantpermissions` table and column `is_superuser` to `true` it all works. I can't figure out why that wasn't being updated when running the earlier commands. At least the issue is fixed.
