### ISSUE TITLE
provision_tenant doesn't use schema_name

### ISSUE THREAD

**Issue by brunoserrar** [Corvia/django-tenant-users#211]
Is there a reason that provision_tenant uses slug instead of schema_name?
Slugs usually have dash and are not compatible with schema names. I could pass schema_name instead but that's being used to create the tenant's domain URL as well.

Anyway,
thanks for this awesome project!

**Comment by daniel-butler** [comment]
The schema name isnt exactly the slug name. The schema has a timestamp added to the end of it. The details can be found [here](https://github.com/Corvia/django-tenant-users/blob/214dd479891c3b3af1669b3ade4464f054d9e82f/tenant_users/tenants/tasks.py#L33).

If you want to change anything you can use that function as a starting point.

**Comment by Dresdn** [comment]
The original authors seem to have made the decision to append the timestamp to the `schema_name` to aid with [delete_tenant()](https://github.com/Corvia/django-tenant-users/blob/214dd479891c3b3af1669b3ade4464f054d9e82f/tenant_users/tenants/models.py#L159). When using `provision_tenant()`, you're not really in control of the Postgres `schema_name`, hence why the param is called `slug`.

If you have a better or more clear name to use, feel free to suggest!

**Comment by Dresdn** [comment]
> The way it is now doesn't allow a subdomain like that.

What version are you using? You should be able to provision a tenant with "sub-domain" as the slug.

> I think maybe it's not a naming issue but that would be nice to have that at the readme or scape special characters before prepending the tenant_slug to the schema name

The usable characters are limited by Postgres and deferred to [django-tenants validating the schema name](https://github.com/django-tenants/django-tenants/blob/5af92a67509eb1bd4a3e17850d369d11d58bd6e4/django_tenants/postgresql_backend/base.py#L34).

The idea would be that the hostname "sub-domain" would by default be the schema name. Perhaps it would help to have an optional param called `schema_name` to allow you to override the schema name matching?

**Comment by brunoserrar** [comment]
> What version are you using?

I'm using the latest release (1.0.0)
The issue happens exactly on the line @[daniel-butler](https://github.com/daniel-butler) pointed out.
There's no "treatment" for a string like "sub-domain" or maybe "sub-domínio" work as a schema name and as tenant domain


> Perhaps it would help to have an optional param called `schema_name` to allow you to override the schema name matching?

I think that would be great! So subdomain names could be more flexible

**Comment by Dresdn** [comment]
> There's no "treatment" for a string like "sub-domain" or maybe "sub-domínio" work as a schema name and as tenant domain

@brunoserrar - There might be a disconnect, as these all should work. Are you using the latest `django-tenants`? This was resolved in https://github.com/django-tenants/django-tenants/issues/688

```
provision_tenant('Dasher', 'sub-domain', 'primary-user@test.com')
'sub-domain.test.com'
provision_tenant('Dashér', 'sub-domínio', 'primary-user@test.com')
'sub-domínio.test.com'
TenantModel.objects.all()
<QuerySet [<Company: public>, <Company: sub-domain_1648824171>, <Company: sub-domínio_1648824213>]>
```

Regarding the parameter, I was understanding you wanted a "sub-domain" to have a schema "sub_domain" - is this not the case?

**Comment by brunoserrar** [comment]
> Regarding the parameter, I was understanding you wanted a "sub-domain" to have a schema "sub_domain" - is this not the case?

It isn't, sorry I didn't make myself clear! Updating `django-tenants` to the latest version solved it.
Thanks for your time
