### ISSUE TITLE
How to add created user to specific tenant(s)?

### ISSUE THREAD

**Issue by hemulin** [Corvia/django-tenant-users#22]
So, I'm struggling with something that supposedly should be rather straight forward.

I have a public scheme and public_tenant.
I also have a tenant provisioned using a previously created TenantUser.

Now I wish to add a newly created user to that newly provisioned tenant.

Tried with the suggestion [here](https://github.com/Corvia/django-tenant-users/issues/13#issuecomment-363124391) but get error:
`AttributeError: 'TenantUser' object has no attribute 'schema_name'`

Then tried from the shell:
```
>>> cl = Client.objects.all()
>>> cl
<TenantQueryset [<Client: Public Tenant>, <Client: ExampleOrganization>]>
>>> user = TenantUser.objects.create_user(email="user2@example.com", password='password', is_active=True, is_staff=True)
>>> user
<TenantUser: user2@example.com>
>>> user.tenants.all()
<TenantQueryset [<Client: Public Tenant>]>
>>> user.tenants.add(cl[1])
>>> user.save()
>>> user.tenants.all()
<TenantQueryset [<Client: Public Tenant>, <Client: ExampleOrganization>]>
```

But then when I try to access the front of that tenant (Client) using that user cred, I get the following error
`RelatedObjectDoesNotExist: TenantUser has no userprofile.`

Can someone please explain me what am I doing wrong and how to fix it?

Cheers

**Comment by Viatrak** [comment]
Try tenant.add_user(user)
