### ISSUE TITLE
delete() got an unexpected keyword argument 'force_drop'

### ISSUE THREAD

**Issue by tyrion** [Corvia/django-tenant-users#26]
Hello, I am trying to delete an user with `force_drop=True`, but [the code of `tenant_users.tenants.model.UserProfile.delete`](https://github.com/Corvia/django-tenant-users/blob/cb1a35328991cf0b4eeb74ddf7f2a6e9f7a97aa7/tenant_users/tenants/models.py#L338) is passing the parameter up when calling super, but `django.db.models.base.Model.delete` does not accept such parameter.

**Comment by Viatrak** [comment]
Can you submit a PR that does not pass up the force_drop=True parameter to the base class?

Unless you have a good reason to delete a user directly with force drop, you should probably use the UserProfileManager method delete_user()

**Comment by tyrion** [comment]
I submitted a PR, let me know if it is ok

**Comment by Viatrak** [comment]
Resolved by https://github.com/Corvia/django-tenant-users/pull/28
