### ISSUE TITLE
Make PermissionsMixinFacade._get_tenant_perms public

### ISSUE THREAD

**Issue by tyrion** [Corvia/django-tenant-users#27]
I was trying to edit the staff status of an user through the shell but I got the `AttributeError` mentioned in issue #20 .

By reading a bit of the code, I managed to do what I needed with:
```python
>>> from django.db import connection
>>> connection.set_tenant(my_tenant)
>>> perms = my_user._get_tenant_perms()
>>> perms.is_staff = True
>>> perms.save()
```

I have the following suggestions:
* I think it would be good to raise a more helpful error message to instruct the user that the `is_staff`/`is_superuser` properties are not writable and point them in the right direction.
* I think a good direction could be to make `get_tenant_perms()` public (i.e. removing the leading underscore) and maybe add some documentation about it in the README.
* An other thing to consider could be to make `get_tenant_perms` a [`cached_property`](https://docs.djangoproject.com/en/2.1/ref/utils/#django.utils.functional.cached_property) and name it for example `tenant_perms` (right now everytime I access `is_staff` a query is made which could be avoided)

An other solution instead of making `_get_tenant_perms` public, could be to enable transparently saving `is_staff` to the current `UserTenantPermissions`, but I don't think it is the best approach since it would require an implicit UPDATE query everytime we set `is_staff`/`is_superuser` (explicit is better than implicit)

I could probably submit a PR if you're interested
Thanks!

**Comment by Viatrak** [comment]
Currently there is an open PR for adding @cached_property. See: https://github.com/Corvia/django-tenant-users/pull/25

If you could review & help test that PR I am open to merging it in as I think it's a great idea.

One of the reasons that those properties were not made writeable is that they may actually not exist if the user hasn't been added to the current tenant. If you look at the code you can see the comments tied to _get_tenant_perms() (which may not exist for a user if the user isn't part of the current tenant).

Submit a PR for this if you have some ideas to solve it or error and documentation updates.

Thanks!
