### ISSUE TITLE
Adding user with separate password for separate tenant possible?

### ISSUE THREAD

**Issue by nikolas-dev** [Corvia/django-tenant-users#278]
Is it possible separate users in separate tenant? Please give an example how to add this

**Comment by Dresdn** [comment]
Hi @nikolas-dev. If you want to have different User objects (with separate passwords) *per* tenant, then I would suggest simply not using this project, as that behavior is the default for `django-tenant`. You'd just need to put whatever app holds your user model into the TENANT portion of your settings.

**Comment by nikolas-dev** [comment]
But, I want a global user who can create tenant and can also manage their data (crud). And every tenant will have their separate data including user. How to achieve that?

**Comment by Dresdn** [comment]
Hi @nikolas-dev - I meant to reply earlier. The short answer is you'll need to write something custom to handle that, as the alternative would be to have two user models, which is really frowned upon.

Based on what you've said, I'd not use this package as the point is to have shared global user data with specific permissions per tenant. Maybe keep it within django-tenants, and then write a custom view/manager/something to create that "super-super user".

Good luck!
