### ISSUE TITLE
Error during installation django-tenant-users

### ISSUE THREAD

**Issue by hosfe** [Corvia/django-tenant-users#284]
I am currently trying to get tenant-client up and running. Which unfortunately doesn't work for me.
How do I proceed:

- new django environment (no data)
- Install django tenant
- Provide companies model
- createssuperuser
- create_tenant
- create_tenant_superuser
- installtion tenants-client
- modify companies model
- create user models
- customize settings.py

Thank you for your feedback

`user = TenantUser.objects.create_user(email="user@evilcorp.com", password='password', is_active=True)`
error:
`  File "<console>", line 1, in <module>
NameError: name 'TenantUser' is not defined`

`python manage.py makemigrations`
error:
`It is impossible to add a non-nullable field 'created' to client without specifying a default. This is because the database needs something to populate existing rows.
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit and manually define a default value in models.py.
Select an option: `

config:

pip list
```
asgiref             3.5.2
Django              4.0.6
django-environ      0.9.0
django-tenant-users 1.0.0
django-tenants      3.4.2
pip                 22.0.4
psycopg2-binary     2.9.3
setuptools          58.1.0
sqlparse            0.4.2
wheel               0.37.1
```

settings.py

```
SHARED_APPS = [
    # Django APP
    'django_tenants',
    # 3rd Party Applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # django-tenant-users apps
    'tenant_users.permissions',
    'tenant_users.tenants',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'companies',
    'users',
]

TENANT_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'tenant_users.permissions',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_USERS_DOMAIN = 'localhost'
AUTHENTICATION_BACKENDS = ('tenant_users.permissions.backend.UserBackend',)
AUTH_USER_MODEL = 'users.TenantUser'

TENANT_MODEL = "companies.Client" # app.Model
TENANT_DOMAIN_MODEL = "companies.Domain"  # app.Model
```

companies - models.py

```
from django.db import models
from django_tenants.models import TenantMixin, DomainMixin

from tenant_users.tenants.models import TenantBase

class Client(TenantBase):
    name = models.CharField(max_length=100)
    paid_until =  models.DateField()
    on_trial = models.BooleanField()
    created_on = models.DateField(auto_now_add=True)
    auto_create_schema = True

class Domain(DomainMixin):
    pass
```

users -models.py
```
from django.db import models

from tenant_users.tenants.models import UserProfile

_NameFieldLength = 100

class TenantUser(UserProfile):

    name = models.CharField(max_length=_NameFieldLength, blank=True)
```

**Comment by Dresdn** [comment]
Hi there. Were you able to make any progress with this?

> `user = TenantUser.objects.create_user(email="user@evilcorp.com", password='password', is_active=True)`
> error:
> ` File "<console>", line 1, in <module> NameError: name 'TenantUser' is not defined`

I'll start with the basics, but did you `from path.to.users.models import TenantUser`?

**Comment by hosfe** [comment]
Hi Dresden,
Thanks for the answer. I don't know where to do this import. I didn't find anything in the documentation.

**Comment by Dresdn** [comment]
I'm not quite sure how to answer this. Importing a model is a core tenant of Python & Django, so since you're getting the `name 'TenantUser' is not defined`, that's python saying "I don't know what this is." That tells me you haven't imported the model to be used.

If you're using the console/shell, you should be able to run `from users.models import TenantUser`.

Otherwise, how are you trying to run the commands?

**Comment by hosfe** [comment]
Currently the first thing I get is this error message:
'Dependency on app with no migrations: users'
Then ./manage.py makemigrations & migrate

Here comes the message
'It is impossible to add a non-nullable field 'created' to client without specifying a default. This is because the database needs something to populate existing rows.
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit and manually define a default value in models.py.
Select an option'

I add the fields:
'timezone.now'

then ./manage.py shell
'from users.models import TenantUser'

no errors

**Comment by mario-moreira** [comment]
Hi @hosfe, I had a similar problem. In my case, i solved the problem deleting the migrations (files 000N_* in migration/ directories) and recreating them again with manage.py makemigrations.
