### ISSUE TITLE
the use of UserProfile is not DRY

### ISSUE THREAD

**Issue by mezitax** [Corvia/django-tenant-users#29]
My customuser inherits from [AbstractUser](https://github.com/django/django/blob/master/django/contrib/auth/models.py#L285), this has the username, lastname and email fields.
For the verification of emails, I use the function of  [django-allauth](https://github.com/pennersr/django-allauth/blob/master/allauth/account/models.py#L20) that is cleaner and more orderly.
If my customuser inherits from UserProfile, I would have to create these fields manually and consider it a "dirty" change.
Is it possible to inherit UserPorfile from some mixin that does not overwrite these fields and only change its behavior ?, maybe a proxi model?

**Comment by Viatrak** [comment]
https://docs.djangoproject.com/en/2.1/topics/db/models/#field-name-hiding-is-not-permitted

> This restriction doesn’t apply to model fields inherited from an abstract model. Such fields may be overridden with another field or value, or be removed by setting field_name = None.

**Comment by Mte90** [comment]
I have the same issue but this ticket is very old...

I have a custom user model with this code:

```
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import PermissionsMixin
from tenant_users.tenants.models import UserProfile
from django.db import models


class User(AbstractUser, PermissionsMixin, UserProfile):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=25, unique=True)
    is_active = models.BooleanField(default=True)

    REQUIRED_FIELDS = ["email"]
    USERNAME_FIELD = "username"
    EMAIL_FIELD = "username"
```

I get this error:
```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases AbstractBaseUser, PermissionsMixin, UserProfile
```
