### ISSUE TITLE
UserTenantPermissions Documentation

### ISSUE THREAD

**Issue by thecircleisround** [Corvia/django-tenant-users#295]
There is nothing in the docs on using UserTenantPermissions and it's required use to have global users have access to tenant admin pages. 

Digging through source is fine I suppose but with no references to this requirement, it took me a long time to realize I was not even troubleshooting the right thing...

**Comment by Dresdn** [comment]
Documentation improvements are great. We welcome any PRs to help improve.

**Comment by MaximShteygervald** [comment]
@thecircleisround did you figure out how to access tenant related admin site? I can only access public schema and all tenan related models noted as "Not available for global schema". Admin site doesn't accept my login credentials under MY-TENANT.example.com/admin URL.

Could you provide your settings directly in this discussion? Writing documentation can be a long process.

**Comment by thecircleisround** [comment]
Yes, you have to access the users usertenantpermissions and set your is_staff permissions to True

```
from users.models import USERMODEL
from tenants.models import TENANTMODEL 
from tenant_users.permissions.models import UserTenantPermissions 
from django_tenants.utils import tenant_context 
from psycopg2.errors import UniqueViolation 

tenant =  TENANTMODEL.objects.all()
user = USERMODEL.objecs.get(pk=[USER_PK])


for tenant in tenants:
    with tenant_context(tenant):
        try: 
            tenant.add_user(user)
        except UniqueViolation: 
            print('User already exists')
        user.usertenantpermissions.is_staff = True
        user.save()
```
You are also able to use ```UserTenantPermissions.objects.get_or_create(profile=user, is_staff=True)``` instead of modifying the is_staff attribute directly on the user, but I sometimes ran into UniqueViolation exceptions trying to do it that way.

**Comment by Dresdn** [comment]
Closing with the launch of https://django-tenant-users.rtfd.io/
