### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jgranek** [Corvia/django-tenant-users#3]
When I'm writing tests for all my apps (models/forms/views) I assume I need to first set up the public tenant, and a test tenant to run all my tenant_apps on?... Do you have any experience writing tests with DTU and django-tenants?

**Comment by Viatrak** [comment]
http://django-tenants.readthedocs.io/en/latest/test.html
http://django-tenant-schemas.readthedocs.io/en/latest/test.html

**Comment by jgranek** [comment]
Oh awesome! thanks!
