### ISSUE TITLE
I suggest a small change in the documentation

### ISSUE THREAD

**Issue by mezitax** [Corvia/django-tenant-users#30]
I had many problems trying to find out why, when I logged in correctly, django returned to the login page without any errors. The problem was here
`SESSION_COOKIE_DOMAIN = '.mydomain.com'`
When entering the web without "www", there is no point before the domain, so you can only enter the admin with subdomain but not the admin of the general website (without subdomain), I suggest changing this line in the documentation to
`SESSION_COOKIE_DOMAIN = 'mydomain.com'`
To take the first steps without errors

**Comment by Dresdn** [comment]
Resovled with https://django-tenant-users.readthedocs.io/en/latest/pages/installation.html#optional-settings
