### ISSUE TITLE
where is the field is_staff?

### ISSUE THREAD

**Issue by mezitax** [Corvia/django-tenant-users#31]
I do not understand where the field is_staff in the configured user, or do I have to add it to my CustomUser manually?
in:
```
users/models.py

from tenant_users.tenants.models import UserProfile

class TenantUser(UserProfile):
    name = models.CharField(
        _("Name"),
        max_length = 100,
        blank = True,
    )
```

UserProfile does not have the field is_staff

https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/models.py
`class UserProfile(AbstractBaseUser, PermissionsMixinFacade):`

UserProfile inherits from AbstractBaseUser but it does not have the is_staff field either (AbstractUser yes)

https://github.com/django/django/blob/master/django/contrib/auth/base_user.py#L47

So, what am I missing?, where is the field is_staff? or maybe I need to add it manually to my CustomUser?
I'm a little lost at this point

**Comment by ivissani** [comment]
`is_staff` is part of the `UserTenantPermissions` class. As its docstring states:
    
```python
    """
    This class serves as the authorization model (permissions) per-tenant.
    We keep all of the global user profile information in the public tenant
    schema including authentication aspects. See UserProfile model.
    """
```

So `is_staff` is stored per-tenant so that a use can be staff in some tenants and not staff in some other tenants

**Comment by mezitax** [comment]
wow thanks, that explains why I could not find it or manipulate it in the admin
