### ISSUE TITLE
Interando com "django-rest-token"

### ISSUE THREAD

**Issue by MagnaldoMelo** [Corvia/django-tenant-users#34]
Gentlemen,
I would like to adapt the project for use with a system using the "django-rest-framework".
Does anyone have any idea how to make the token generated on the specific tenant?
Thanks!

**Comment by Viatrak** [comment]
Django Rest Framework should work fine without any modifications. With this package, authentication and authorization are separated. The user authentication (token) is still global, so you do not need to generate tokens for each tenant. But for that global user, unique permissions can be applied inside each tenant.
