### ISSUE TITLE
Why is removing an inactive user from a tenant not supported?

### ISSUE THREAD

**Issue by philippbosch** [Corvia/django-tenant-users#35]
I have an inactive (`user.is_active == False`) user that I want to remove from a tenant. This is prohibited [here](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/models.py#L111). Could somebody elaborate why that is the case? Or how I should go about removing the user from the tenant? `user.tenants.remove(tenant)`?

**Comment by philippbosch** [comment]
ping @Viatrak maybe?

**Comment by Viatrak** [comment]
Hrmm.

**Comment by Viatrak** [comment]
I can't think of any good reasons to have that check remain there. In fact, it seems incorrect for it to be there.

I think you should submit a PR to remove that. Before I accept the pull I will investigate a bit more.

**Comment by philippbosch** [comment]
@Viatrak Here's the PR: #36 
I tried it in my project and could successfully (and with no obvious side effects) remove inactive users.

**Comment by philippbosch** [comment]
@Viatrak any chance you could have a look at this PR? ☝️

**Comment by philippbosch** [comment]
Thank you!
