### ISSUE TITLE
Support for multi type tenants

### ISSUE THREAD

**Issue by mihnen** [Corvia/django-tenant-users#354]
## Detailed Description
 django-tenants supports multiple types of tenants as described here: https://django-tenants.readthedocs.io/en/latest/use.html#multi-types-tenants. It does not appear this is compatible with django-tenant-users out of the box since the provision_tenant function is used to wrap the creation of tenants and there is no way to pass extra fields to the tenant when it is created, you need to be able to pass the tenant type to the constructor otherwise it can't run the migrations as it doesn't know what apps are installed for that tenant type.

## Possible Implementation
 Modify the provision_tenant function to allow passing extra fields to the users tenant type constructor

**Comment by Dresdn** [comment]
Sounds like a great idea. PRs are always welcome @mihnen!

**Comment by mihnen** [comment]
@Dresdn Will do, I implemented this already just need to add test cases for it, are there instructions somewhere on how to run the test suite?

**Comment by Dresdn** [comment]
@mihnen - Easiest way is via [poetry](https://python-poetry.org/). Once installed, you can run:

- `poetry install`
- `poetry shell`
- `pytest`

Every PR runs pytest on the support matrix, so anything missed should be caught there.

Let me know if you need any help!

**Comment by Dresdn** [comment]
Alternatively, you can push up your changes and let the GitHub Action run the tests too. Either way!
