### ISSUE TITLE
Updating django_tenants Tutorial for django-tenant-users

### ISSUE THREAD

**Issue by trimbleava** [Corvia/django-tenant-users#358]
Provide a general summary of the issue in the title above.

## Detailed Description
 Provide a description of the change or addition you are proposing.

## Context
I am trying to use the live tutorial provided by django_tenants with django-tenant-users. I seem to have problem. 
Is it possible to update that tutorial with your objects? I also need to ask questions which site is that? Thanks
My email is trimbleava@gmail.com  Thanks

## Possible Implementation
 Not obligatory, but you may suggest an idea for implementing addition or change.

**Comment by Dresdn** [comment]
I'm not sure what tutorial you are referring to. If this is something on the `django-tenants` application, you may want to contribute something there.

I would also suggest you look at the [django_test_app](https://github.com/Corvia/django-tenant-users/tree/master/django_test_app) in the project.

**Comment by trimbleava** [comment]
Dear Mike - I would like to thank you all for contributing so greatly to
the developers world. I do not know how you do this job for free!! Please
add a "DONATE" button on your page. I tried to look for it, but found none.
Also thank you very much for replying to my email.

The tutorial I am referring to is  a link in this URL:
https://django-tenants.readthedocs.io/en/latest/examples.html, shown below.

Tenant Tutorial
<https://django-tenants.readthedocs.io/en/latest/examples.html#tenant-tutorial>

This app comes with an interactive tutorial to teach you how to use
django-tenants and to demonstrate its capabilities. This example project is
available under examples/tenant_tutorial
<https://github.com/django-tenants/django-tenants/blob/master/examples/tenant_tutorial>.
You will only need to edit the settings.py file to configure the
DATABASES variable
and then you’re ready to run

./manage.py runserver

*I would love to help but* I have a few questions before I can contribute.
Below is the part in django_tenants interactive tutorial that is not
working after I incorporate django-tenant-user into my code: , I think (not
sure though) due  to use of slug:
{% if request.tenant %}
          <a href="http://{{ request.tenant.get_primary_domain.domain
}}:8008">{{ request.tenant.name }}</a>
          (<code>{{ request.tenant.schema_name }}</code>, <code>{{
request.tenant.get_primary_domain.domain }}</code>).
          &nbsp; &nbsp; &nbsp; &nbsp; Available customers:
        {% else %}
          None
{% endif %}

        {% for tenant in tenants_list %}
          <a href="http://{{ tenant.get_primary_domain.domain }}:8008">{{
tenant.name }}</a> &middot;
        {% endfor %}
      </p>

      <p style="float: right;">
        <a href="https://github.com/tomturner/django-tenants">django-tenants
</a> &middot;
        <a href="https://django-tenants.readthedocs.org/en/latest/">
Documentation</a>
      </p>

**Comment by trimbleava** [comment]
Sorry I was not finished, by mistake I pushed the tab!! I start over.

Dear Mike - I would like to thank you all for contributing so greatly to
the developers world. I do not know how you do this job for free!! Please
add a "DONATE" button on your page. I tried to look for it, but found none.
Also thank you very much for replying to my email.

The tutorial I am referring to is  a link in this URL:
https://django-tenants.readthedocs.io/en/latest/examples.html, shown below.

Tenant Tutorial
<https://django-tenants.readthedocs.io/en/latest/examples.html#tenant-tutorial>

This app comes with an interactive tutorial to teach you how to use
django-tenants and to demonstrate its capabilities. This example project is
available under examples/tenant_tutorial
<https://github.com/django-tenants/django-tenants/blob/master/examples/tenant_tutorial>.
You will only need to edit the settings.py file to configure the
DATABASES variable
and then you’re ready to run

./manage.py runserver

*I would love to help but* I have a few questions before I can contribute.
If you do not mind answering a few questions I would be more than happy to
do so, since I am using these 2 libraries for my work.

Below is the part in django_tenants interactive tutorial that is not fully
working after I incorporate django-tenant-user into my code:

{% if request.tenant %}
          <a href="http://{{ request.tenant.get_primary_domain.domain
}}:8008">{{ request.tenant.name }}</a>
          (<code>{{ request.tenant.schema_name }}</code>, <code>{{
request.tenant.get_primary_domain.domain }}</code>).
          &nbsp; &nbsp; &nbsp; &nbsp; Available customers:
        {% else %}
          None
{% endif %}

        {% for tenant in tenants_list %}
          <a href="http://{{ tenant.get_primary_domain.domain }}:8008">{{
tenant.name }}</a> &middot;
        {% endfor %}
      </p>

      <p style="float: right;">
        <a href="https://github.com/tomturner/django-tenants">django-tenants
</a> &middot;
        <a href="https://django-tenants.readthedocs.org/en/latest/">
Documentation</a>
      </p>

This particular line *<a href="http://{{
request.tenant.get_primary_domain.domain }}:8008">{{ request.tenant.name
<http://request.tenant.name/> }}*</a>
is not showing  where as this line  <a href="http://{{
tenant.get_primary_domain.domain }}:8008">{{ tenant.name }} is working.
I think (not sure though) due to use of slug??
1)
Can you tell me *where in the code* (django_tenants or django-tenant-user
libs) this  tenant.get_primary_domain.domain maps to? I can not find any
get_primary_domain.domain in both codes.

2)
Below are my settings where *our tenants are utility companies* but *my
company does the work on their behalf.*
TENANT_MODEL = "customers.Client"
TENANT_DOMAIN_MODEL = "customers.Domain"
TENANT_USERS_DOMAIN = "lsa.etl.heathus.com" # my company application
(lsa.etl) and domain (heathus.com)
AUTH_USER_MODEL = 'accounts.TenantUser'
AUTHENTICATION_BACKENDS = ('tenant_users.permissions.backend.UserBackend',)
SESSION_COOKIE_DOMAIN = '.mydomain.com'

When I create the tenant user per your tutorial:

# Create public tenant user.
from tenant_users.tenants.utils import create_public_tenant
create_public_tenant(domain_url="my.evilcorp.domain", owner_email="
***@***.***")

*mine is: * create_public_tenant(domain_url="public. lsa.etl.heathus.domain",
owner_email="admin@ lsa.etl.heathus.com ")

and *my tenants is *something like this:

          from tenant_users.tenants.tasks import provision_tenant
          fqdn = provision_tenant(tenant_name="South West Gas (swg)",

 tenant_slug="southwestgasls",
                                                  user_email="
***@***.***")

3)
In the django_tenant tutorial, as shown above, the port to go to the tenant
is *"8008" *-- shouldn't this port be same as the port the main program is
running on?


With the above configuration, as I mentioned the below line of code doesn't
find the link to the tenant even when I use the same port to run the
program.
 *<a href="http://{{ request.tenant.get_primary_domain.domain }}:8008">{{
request.tenant.name <http://request.tenant.name/> }}*</a>

I really appreciate your help. If I can make mine work, I will provide 2
tutorials, one interactive and one web based with views.

Regards
Ava

**Comment by Dresdn** [comment]
Hi @trimbleava - Appreciate the compliments - just my small way of giving back.

For your question, I have to say this isn't the correct place to post the question about that project. I would open an issue over at the [django-tenants](https://github.com/django-tenants/django-tenants) project since your issue is with their tutorial and project.

Best of luck!
