### ISSUE TITLE
Does this Support Multiple Domains not subdomains

### ISSUE THREAD

**Issue by drexhacker** [Corvia/django-tenant-users#365]
I have seen this works alongside django-tenants which I prepare to use but I want to have my main domain to monitor all other domains of my clients and this leads to a need of multi domain support for example I have example.com as the main domain, then I have a client with sample.com as his domain and I would like both example.com and sample.com to able to access the same system but different schemas / access rights. Not forgeting example.com has to manage / monitor sample.com

**Comment by Dresdn** [comment]
The handling of the schema -> domain mapping is all done via `django-tenants`. This project has a direct dependency on that and serves to allow using a single user object with tenant-specific permissions across multiple schemas.

I would suggest you look at the issues and conversations in that project to see if there are examples of folks doing what you need.

That said, doing a quick look at the [middleware](https://github.com/django-tenants/django-tenants/blob/master/django_tenants/middleware/main.py), yes, it does use the hostname by default to do a match on the Tenant. Should be as easy as overriding `TenantMainMiddleware.process_request()`.
