### ISSUE TITLE
How to configure the permission system?

### ISSUE THREAD

**Issue by mezitax** [Corvia/django-tenant-users#38]
So when using django-tenant-users, the groups are now inside the tenant_app and the users in the shared_app.
I want to filter a user according to their group in the public shema
`User.objects.filter (groups__name = "teacher")`
Within each tenant, there are local groups and I will use them for permissions within the tenant.
The groups within the public tenant will be for permissions in shared apps.
So how do I filter the group from the user?

**Comment by Viatrak** [comment]
The currently set schema (tenant, or public) is what will be searched for groups/permissions.

**Comment by mezitax** [comment]
> The currently set schema (tenant, or public) is what will be searched for groups/permissions.

I understand that
My question is how to access user.groups
I want to programmatically add users to groups within a tenant

**Comment by Viatrak** [comment]
Here is an example in the code where it uses the groups (in this case to remove the user from all groups):

https://github.com/Corvia/django-tenant-users/blob/4ff5d7293436c720f1af567a8088ac1305502c8c/tenant_users/tenants/models.py#L118

Hope that helps.

**Comment by mezitax** [comment]
Thanks, that line helped me
I already managed to assign the permissions at the programmatic level, however I still think about something.
django-tenant-users breaks the `user.groups` connection, within a tenant there are only tenant groups, so i think this seems easy to solve:
`class CustomUser (UserProfile):
         def groups (self):
                 return self.usertenantpermissions.groups`
The problem arises when certain apps want to create groups with:
`user.groups.add (group)`
How can I fake the groups.add function (as opposed to groups.clear ())to a specific group?
I would like to keep this line working in the current tenant:`user.groups.add (group)`

**Comment by JupiterThreads** [comment]
> Thanks, that line helped me
> I already managed to assign the permissions at the programmatic level, however I still think about something.
> django-tenant-users breaks the `user.groups` connection, within a tenant there are only tenant groups, so i think this seems easy to solve:
> `class CustomUser (UserProfile):          def groups (self):                  return self.usertenantpermissions.groups`
> The problem arises when certain apps want to create groups with:
> `user.groups.add (group)`
> How can I fake the groups.add function (as opposed to groups.clear ())to a specific group?
> I would like to keep this line working in the current tenant:`user.groups.add (group)`

Am I missing something… can’t you just make it a property? That’s what I’ve done and it works fine.

```
@property
def groups(self):
     return self.usertenantpermissions.groups
```

**Comment by Dresdn** [comment]
Closing due to age
