### ISSUE TITLE
Unable to successfully login to django in any of public/other tenant

### ISSUE THREAD

**Issue by humblesami** [Corvia/django-tenant-users#39]
Read me or sample code never guided the exact format/order of instructions for tenant creations so I am trying mine according to given guidelines to create tenants with code in one of my shared app view

Created public tenant
`
                    public_owner = "owner@local"
                    create_public_tenant("localhost", public_owner)
                    tenant_admin_email = "admin@local"
                    TenantUser.objects.create_superuser('123', tenant_admin_email)
` 
Created my tenant
 ``
                   tenant_admin_email = "admin@" + tenant_name
                    TenantUser.objects.create_superuser('123', tenant_admin_email)
                    provision_tenant(tenant_name, tenant_name, tenant_admin_email)
``
It does all => creates tenant with schema and both the super users as well

But access to admin panel on public never succeeds (even login gets the user) with zero message
And in tenants it always gives message as "Please enter the correct Email Address and password"

My settings are as
`
MIDDLEWARE = (
    'tenant_tutorial.middleware.TenantTutorialMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Uncomment the next line for simple clickjacking protection:
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

TENANT_MODEL = "customers.Client"  # app.Model
TENANT_DOMAIN_MODEL = "customers.Domain"  # app.Model
TENANT_USERS_DOMAIN = "localhost"
AUTH_USER_MODEL = 'users.TenantUser'
AUTHENTICATION_BACKENDS = (
    'tenant_users.permissions.backend.UserBackend',
)
SESSION_COOKIE_DOMAIN = '.' + TENANT_USERS_DOMAIN

SHARED_APPS = (
    'django_tenants',
    'django.contrib.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'customers',  # you must list the app where your tenant model resides in
    'users',
)

TENANT_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'tenant_users.permissions',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'tenant_only',
)

INSTALLED_APPS = list(set(TENANT_APPS + SHARED_APPS))
`

**Comment by Guest007** [comment]
hi

You have trouble in this: `TENANT_USERS_DOMAIN = "localhost"`

I don't try tenant_schemas, but with django-tenants domain must contain two dot-separated part (or more). Try `TENANT_USERS_DOMAIN = "local.localhost"`

**Comment by bmoe872** [comment]
I'm having a very similar problem. My second tenant is setup at `test.localhost:5000` and I can view `test.localhost:500/admin` just fine, but when logging in, it keeps saying I need a staff or active account. 

I then tried to login to the base `localhost:5000/admin` and was met with an error that says:

```
You are authenticated as admin@test.com, but are not authorized to access this page. Would you like to login to a different account?
```

This is after trying to login to `test.localhost:5000` with that email - so I'm logging in, but somehow don't have permissions to view the admin?

**Comment by pickyuptruck** [comment]
Has anyone managed to solve this? I am having the same problem as @humblesami .

I have tried:

- putting `TENANT_USERS_DOMAIN = "local.localhost"` in settings
- logging in with a user where is_staff=True **for the particular schema whose admin page I am trying to access**

If I try to log in with incorrect credentials or a user with `is_staff=False`, it returns an error. This is expected:
<img width="434" alt="Screenshot 2020-04-22 at 18 12 54" src="https://user-images.githubusercontent.com/53524720/80012231-e47bda80-84c4-11ea-9617-4c2e046c2f05.png">


However, if I 'successfully' log in with an `is_staff=True` user and the right credentials, it simply redirects me to the login page, instead of displaying the admin dashboard. There is no error message:
<img width="449" alt="Screenshot 2020-04-22 at 18 17 58" src="https://user-images.githubusercontent.com/53524720/80012681-9a472900-84c5-11ea-9548-3dc891536c42.png">

From settings.py:

```
SHARED_APPS = (
    'django_tenants',
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'social_django',
    'corsheaders',
    'core',
    'users',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'tenant_users.permissions',
    'tenant_only',
)

INSTALLED_APPS = list(SHARED_APPS) + \
    [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "core.Tenant"

TENANT_DOMAIN_MODEL = "core.Domain"

TENANT_USERS_DOMAIN = "local.localhost"

SESSION_COOKIE_DOMAIN = '.localhost'

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

I'm pretty new to this, so I'd really appreciate any help!

**Comment by Jaquedeveloper** [comment]
Same problem here, any solution or clue?

**Comment by oksim14** [comment]
Did you guys figure it out?

**Comment by FloOpps** [comment]
Same problem than @pickyuptruck , if someone have a solution please ^^

**Comment by Guest007** [comment]
Are you set `test.localhost` or `local.localhost` or similar (all that you want to use) in your system `hosts` file?
Something like 
```
127.0.0.1  localhost
127.0.0.1  test.localhost
127.0.0.1  local.localhost
```

**Comment by FloOpps** [comment]
Hey, it does not work ^^
![image](https://user-images.githubusercontent.com/55506245/117625792-af493580-b176-11eb-8531-3252e197c3c8.png)

**Comment by JupiterThreads** [comment]
I think you need to grant whatever user you are trying to sign in with permissions on that tenant. I have a permissions_usertenanttpermissions table in one my tenants, and I created a new entry for my user (userprofile) and made them a super user and staff. After doing that I managed to log in to a tenant's admin dashboard.

**Comment by detodotl** [comment]
After executing this command in manage.py shell

`from tenant_users.tenants.utils import create_public_tenant
create_public_tenant("localhost", "admin@evilcorp.com")`

¿Do i have to do something else?
¿What password is it assigned? (I see set_unusable_password is called, ¿how can i change the password then?
¿Do i have to create first a superuser? (createsuperuser command doesn´t work for me. Error: User matching query does not exist)

**I can not log in to the public tenant, it says i need an staff account**

Sorry if iam asking a very basic question, i am learning django. Thanks

**SETTINGS**
`ALLOWED_HOSTS = ['localhost', 'www.localhost', '.localhost', '127.0.0.1']


# Application definition

SHARED_APPS = [
    'tenant_schemas',
    'rest_framework',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',

    'tenant_users.permissions',
    'tenant_users.tenants',

    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'client',
    'users',
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'tenant_users.permissions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tenant',
]

INSTALLED_APPS = (
    'tenant_schemas',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'tenant_users.permissions',
    'tenant_users.tenants',

    'rest_framework',

    'client',
    'tenant',
    'users',
)

SITE_ID=1

TENANT_MODEL = 'client.Client'
TENANT_USERS_DOMAIN = 'localhost'
AUTH_USER_MODEL = 'users.TenantUser'
AUTHENTICATION_BACKENDS = ('tenant_users.permissions.backend.UserBackend',)

if DEBUG:
    SESSION_COOKIE_DOMAIN = 'None'
else:
    SESSION_COOKIE_DOMAIN = '.yourdomain.com'

MIDDLEWARE = [
    'tenant_schemas.middleware.DefaultTenantMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]`

**Comment by chrishowes** [comment]
For me, the issue was: `SESSION_COOKIE_DOMAIN = ".localhost"`. 

It's not a django-tenant-users issue, or a django-tenant issue. It's just a web issue - you can't have `.localhost` as a valid session domain. https://code.djangoproject.com/ticket/10560

Removing this solved, but now I can't stay logged in across domains. But that's probably outside the scope here.

**Comment by detodotl** [comment]
@JupiterThreads, @Dresdn, thank you so much!
