### ISSUE TITLE
TENANT_DB_ALIAS improperly configured

### ISSUE THREAD

**Issue by xtechgamer735** [Corvia/django-tenant-users#436]
I am getting the following issue when attempting to create public tenant for the first time following the steps in this repo. The project is a blank project using Postgres.

Code used is:
`from tenant_users.tenants.utils import create_public_tenant
create_public_tenant(domain_url="public.backend.com", owner_email="admin@evilcorp.com")`

https://pastebin.com/9RnXcqwC

From my understanding this just relates to the default database, which is working since I have migrated successfully and can see its fine.

## Expected Behavior
Public tenant should be created.

## Actual Behavior
https://pastebin.com/9RnXcqwC

## Possible Fix
Not obligatory, but you can suggest a fix or reason for the bug.

## Steps to Reproduce
Installing Django-tenants and django-tenants-users in a blank project as per user guide.

## Your Environment
Include relevant details about the environment you experienced the bug in.

* Version used: 1.1.1
* Environment name and version (e.g. Django 3.2.15, pip 9.0.1): Django 4.1.9, pip 23.1.2
* Operating System and version: MacOS 12.6

Thanks a lot!

**Comment by Dresdn** [comment]
What is your `DATABASES` setting? By default, `django.db.DEFAULT_DB_ALIAS` is a constant that returns `default` as the value. If [you've named this something other than "default"](https://docs.djangoproject.com/en/4.2/ref/databases/#postgresql-connection-settings), you'll need to define the setting `TENANT_DB_ALIAS` so **django-tenants** knows what database to use.

**Comment by xtechgamer735** [comment]
> What is your `DATABASES` setting? By default, `django.db.DEFAULT_DB_ALIAS` is a constant that returns `default` as the value. If [you've named this something other than "default"](https://docs.djangoproject.com/en/4.2/ref/databases/#postgresql-connection-settings), you'll need to define the setting `TENANT_DB_ALIAS` so **django-tenants** knows what database to use.

Thanks for the quick reply! Database settings as below:
 `# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'django',
        'USER': 'django',
        'PASSWORD': 'django',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)`

That's my understanding too, its strange its not picking up default, even been checking my spelling!

**Comment by Dresdn** [comment]
More than happy to help, but probably `django-tenants` would be a more appropriate place to start since this is more to do with the database connection side.

That said, I would maybe fire up a `manage.py shell` and check the following to see what it returns:

```
from django.conf import settings
from django.db import DEFAULT_DB_ALIAS

getattr(settings, DEFAULT_DB_ALIAS)
```

See what it returns?

**Comment by Dresdn** [comment]
I actually tried this and realized I was wrong in my prior note.

What does this show for you?

```
from django_tenants import utils
utils.get_tenant_database_alias()
```

I get: `'default'` which is expected.

This is where I'm looking btw https://github.com/django-tenants/django-tenants/blob/master/django_tenants/utils.py#L28

**Comment by xtechgamer735** [comment]
Hey @Dresdn thanks so much for your help,

In the end I undid everything, reset my db and then re-setup both Django-tenants and Django-tenants-users which seemed to solve it, very strange!

Additionally, I have a few questions regarding the admin functionality using this system. I'll open a new ticket :)
