### ISSUE TITLE
Why doesn't create_public_tenant return the tenant it created?

### ISSUE THREAD

**Issue by boatcoder** [Corvia/django-tenant-users#44]
Would be slightly more like django `get_or_create` returning the object it created.

I can make a PR if needed.

**Comment by Viatrak** [comment]
PR's are always welcome and will be reviewed as time permits! Thanks

**Comment by boatcoder** [comment]
So there is no specific reason for this?  It doesn't violate some plan or
idea within the project?

**Comment by Dresdn** [comment]
Resolved in v1.3.0
