### ISSUE TITLE
A user from another tenant can access a different tenant when logged in

### ISSUE THREAD

**Issue by speightashley** [Corvia/django-tenant-users#485]
I have a public tenant and another tenant called test which is accessible through test.dev.localhost

I have test@test.com as user one who belongs to the test.dev.localhost tenant and is the owner of that tenant

I have another user test@test2.com who doesn't own any tenant and isn't a member of any tenant except the public tenant.

When I have a loginrequired mixin on the view for the tenant, I need to be logged in to view the tenanted site. The issue is, I can be logged in as either test@test.com or test@test2.com and they can both access the test tenant.

I've tried doing this in a private browser because of cookies and it's still the same. 

Am I missing something?

Thanks in advance

Ash

**Comment by Dresdn** [comment]
That's a great call out, and no, you're not missing anything. Here's some middleware that will prevent exactly that:

```
from django.http import Http404
from django.utils.functional import cached_property

class TenantAccessMiddleware:
    """Access to requested tenant middleware."""

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if request.user.is_authenticated:
            if not self.has_tenant_access(request):
                raise Http404("Page not found")
        return self.get_response(request)

    def has_tenant_access(self, request):
        return request.user.tenants.filter(id=request.tenant.id).exists()
```

This probably should be part of the official app too.

**Comment by speightashley** [comment]
Thanks again brother. Appreciate it :)

**Comment by speightashley** [comment]
I've just had a play with this this morning and noticed something on my end which I think I've messed up. When I created the public tenant, I used create_public_tenant() and called it public.dev.localhost.

Now when I do a dir(request) to see the attributes, there is no tenant attribute on the request for dev.localhost.

I therefore can't test ownership of the pubic tenant against a user.

I took the pubic tenant instructions from the docs.

Any advice on that one?

Thanks

Ash

**Comment by Dresdn** [comment]
I'm going to assume you're inspecting the `request` object in the view, so all the middleware has run. If you're not seeing the `request.tenant`, you'll need to check the `django-tenants` setup as [their middleware is what adds the tenant param on the request object](https://github.com/django-tenants/django-tenants/blob/master/django_tenants/middleware/main.py#L50).

**Comment by Dresdn** [comment]
I wanted to check one more thing and saw this too: Check out the `context_processors` note at https://django-tenants.readthedocs.io/en/latest/install.html#basic-settings

**Comment by speightashley** [comment]
Got it mate. That's perfect. Running really well now :-D

I'm going to open another issue for something else now though. It's not really an issue.... just a suggestion. :)
