### ISSUE TITLE
Delete tenant

### ISSUE THREAD

**Issue by chacatico** [Corvia/django-tenant-users#49]
Hi, im try to delete a tenant and the schema in posrtgresql, can anyone help me whit this? thanks...

**Comment by tomturner** [comment]
You don't have to do it with SQL. If you have auto_drop_schema set in your tenant model. When you remove the record in you tenant model it will delete the schema however if you do want to drop a tenant in SQL do the following

`DROP SCHEMA schema_name`

**Comment by chacatico** [comment]
thanks...
