### ISSUE TITLE
Is it required to install django-tenants or django-tenants-schema to use this?

### ISSUE THREAD

**Issue by Vineet-Sharma29** [Corvia/django-tenant-users#51]
In docs, it's written that it's made to work alognside django-tenants or django-tenant-schema. So do i need to install any one of them too?

**Comment by Viatrak** [comment]
Yes, you need to use one or the other alongside this. Those packages provide the tenant framework and will operate independently of this package but the users/permissions are isolated to each tenant and thus you cannot have a user that operates on multiple tenants. This repository adds support for global users to all tenants in the django tenants or django tenants schemas packages.
