### ISSUE TITLE
Fully functioning example

### ISSUE THREAD

**Issue by stfeirer** [Corvia/django-tenant-users#518]
could you post a full features example django app using django-tenants and django-tenants-users.  I am having issues getting them both to work together using the documention provided.

**Comment by Dresdn** [comment]
What issues are you having? Have you looked at the [django_test_app](https://github.com/Corvia/django-tenant-users/tree/master/django_test_app)? This is a fully functioning app that's used for testing.

**Comment by adnannazir** [comment]
![image](https://github.com/Corvia/django-tenant-users/assets/6734301/36ae1897-850b-4437-ace0-eb2514e3c44a)

I am seeing users in public schema only. Is this intended? How is it helping with seperating users data?

**Comment by adnannazir** [comment]
**TENANT_USERS_DOMAIN = "localhost"**
Hi, In django-tenants, one can use the localhost for testing like demo.localhost etc
I am not able to load the correct tenant in localhost.

**Comment by Dresdn** [comment]
The comment is off-topic @adnannazir. Can you please open a new issue for your topic?

**Comment by Dresdn** [comment]
Closing due to lack of response @stfeirer. Feel free to re-open or create a new issue with any specific issues you're facing.
