### ISSUE TITLE
access the table users_user_tenants

### ISSUE THREAD

**Issue by msaustral** [Corvia/django-tenant-users#523]
Hi there is no information on how to access the table users_user_tenants (model) so que can add more users to grant access to a tenant at the admin panel.

we need to add more users to this table, can you help us?

**Comment by Dresdn** [comment]
Adding user accounts themselves is done by creating `TenantUser` objects. To grant a user account access to a tenent, you can use [`TenantBase.add_user()`](https://django-tenant-users.readthedocs.io/en/latest/_modules/tenant_users/tenants/models.html#TenantBase.add_user) if you want permissions.

Since your question is doing this from the Admin Panel, there isn't a method to do that. You'll need to write an admin view to do this.

**Comment by msaustral** [comment]
Hi thank you for your fast response.

On the example test is not showing this function and also there is no information on how to use it on the docs.

Can you help us with an example?

**Comment by Dresdn** [comment]
I linked this in my prior comment: https://django-tenant-users.readthedocs.io/en/latest/_modules/tenant_users/tenants/models.html#TenantBase.add_user

**Comment by msaustral** [comment]
Hi we manage to add the user to the tenant but we can not login on the tenant admin panel with that user, any idea?

SHARED_APPS = (
    'django_tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'tenant',
    'users',
    'core',
) 

TENANT_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'tenant_users.permissions',
    'rest_framework',
) + LOCAL_APPS

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

**Comment by Dresdn** [comment]
The permissions are handled in the `UserTenantPermissions` object that's created per tenant, so access properties like `is_superuser` or `is_staff` is handled on that object.

You can set these on the `UserTenantPermissions` object for the given user, or during creating by [setting params for `add_user()`](https://github.com/Corvia/django-tenant-users/blob/1.3.0/tenant_users/tenants/models.py#L93)

**Comment by msaustral** [comment]
Hi we have 1 user (is_staff and is_superuser = True), 2 tenant (public, tenant1)

On public we can access de admin panel and all works perfect
On the tenant1 with the same user, we can not login

**Comment by Dresdn** [comment]
Here's steps you can take to see what the permissions are for the user in a given tenant:

```
python manage.py tenant_command shell (or shell_plus)
<pick your tenant>
user = YourUserModel.objects.get(...)
user.usertenantpermissions.__dict__
```

Then you can compare that with what the public tenant has by just running `python manage.py shell`

**Comment by msaustral** [comment]
Hi there was missing permission is_staff and is_superuser on the tenant 

Thank  you
