### ISSUE TITLE
How to successfully run it on the localserver?

### ISSUE THREAD

**Issue by adnannazir** [Corvia/django-tenant-users#529]
I am in process of working on an application where I have clients that can have clients, so I thought, I should use django_tenants for the purpose of better organization. 
I also need authorization so I came across this package from the django_tenants documentation. This package actually simplies few things but what I am not able to achieve is that without any issue, I can run the django_tenants on local server. but when I am using django_tenant_users, I am not able to run the tenant_based apps like _demo.localhost:8000_ isn't giving me anything, not even django debug page but a page with following error.
![image](https://github.com/Corvia/django-tenant-users/assets/6734301/8103f5cc-3ef8-44ae-8341-a4f379595259)

Can you please help me ? I am using provision_tenant for tenant creation, do I still need to create domain like in django_tenant?
also there is a little typo in the docs. we don't 
utilize the [utils.create_public_tenant()](https://django-tenant-users.readthedocs.io/en/latest/pages/utilities.html#tenant_users.tenants.tasks.provision_tenant) function: but provison_tenant
![image](https://github.com/Corvia/django-tenant-users/assets/6734301/c7a1a7e1-0017-46ea-8d3e-8b34c5837425)

**Comment by adnannazir** [comment]
Thanks a lot for the response. 
I have configured django-tenants and django-tenant-users according to the instruction, double checked the middleware part as well. Yes Domain.objects.all() has my demo.localhost in it.
![image](https://github.com/Corvia/django-tenant-users/assets/6734301/c1b819f7-3878-4cd1-8b83-a7986fb32c34)

Do I need to create it with shell (I am using the management command for this purpose) should this be necessary ? I followed the interactive tutorial of the django-tenants and one can create tenants with the code. 
here is my management command code. 

`from django.core.management.base import BaseCommand

from accounts.models import Customer, User
from tenant_users.tenants.tasks import provision_tenant
from tenant_users.tenants.utils import create_public_tenant


class Command(BaseCommand):
    help = "Initialize tenant"

    def handle(self, *args, **kwargs):
        # create your public tenant
        if Customer.objects.filter(schema_name="public").first():
            return

        create_public_tenant(domain_url="localhost", owner_email="adnan@codevstan.com",
                             tenant_extra_data={"code": "public"}, password="test2023")

        self.stdout.write(self.style.SUCCESS('Default Tenant created successfully.'))
        User.objects.create_user("ad@codevstan.com", "A1234", True)
        provision_tenant("demo1", "demo", "ad@codevstan.com", tenant_extra_data={"code": "demo"})
        self.stdout.write(self.style.SUCCESS('demo Tenant created successfully.'))
`

**Comment by adnannazir** [comment]
Thanks a lot for the response.
I have configured django-tenants and django-tenant-users according to the instruction, double checked the middleware part as well. Yes Domain.objects.all() has my demo.localhost in it.
image

TENANT_USERS_DOMAIN is also set to localhost.
Do I need to create it with shell (I am using the management command for this purpose) should this be necessary ? I followed the interactive tutorial of the django-tenants and one can create tenants with the code.
here is my management command code.

`
from django.core.management.base import BaseCommand
from accounts.models import Customer, User
from tenant_users.tenants.tasks import provision_tenant
from tenant_users.tenants.utils import create_public_tenant

class Command(BaseCommand):
	help = "Initialize tenant"

	def handle(self, *args, **kwargs):
		# create your public tenant
		if Customer.objects.filter(schema_name="public").first():
			return

		create_public_tenant(domain_url="localhost", owner_email="adnan@codevstan.com",
							 tenant_extra_data={"code": "public"}, password="test2023")

		self.stdout.write(self.style.SUCCESS('Default Tenant created successfully.'))
		User.objects.create_user("ad@codevstan.com", "A1234", True)
		provision_tenant("demo1", "demo", "ad@codevstan.com", tenant_extra_data={"code": "demo"})
		self.stdout.write(self.style.SUCCESS('demo Tenant created successfully.'))
`

**Comment by Dresdn** [comment]
> need to create it with shell

What is "it" in this statement? If you mean the public tenant, no, you can create it however you want. Using the management command like you have works too (and is honestly something we should add to the package!)

Based on what you have, after doing that, you'll have to go to `http://localhost:<port>` as the [slug/tenant matching is based on the request](https://github.com/django-tenants/django-tenants/blob/master/django_tenants/middleware/main.py#L37).

Personally, and what I recommend to my team, is to configure a local resolver for `.test` domain (using dnsmasq, etc.) that just has it so `any.hostname.used.test` is automatically resolved to `127.0.0.1` which is where Django is listening on. Then, set up the local environment with `customer.test` as the "Public" domain and then go from there. I also front everything with Caddy to make HTTPS easy too.

I think that's just less confusing than `localhost`, `foo.localhost`, and `bar.localhost` - just purely my 2c!

**Comment by adnannazir** [comment]
With **it** I meant the tenant created via provision_tenant() function. I am wrapping my head around but still not able to run it on my project. I am not sure, what exactly am I missing. I even merged the test/example apps from django_tenants and django_tenant_users, which is working fine. https://github.com/adnannazir/tenants_plus_users

I am running my project on docker, can that be of any issue? https://github.com/adnannazir/django_tenants_usage

**Comment by Dresdn** [comment]
I chose to use your `tenants_plus_users` repo. Cloned it, created a venv, installed the `requirements.txt`, set the local `DATABASE_*` env vars, and created the database. From there, here's what I see:

## Provision Database
```
❯ python manage.py migrate              
[standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: admin, auth, contenttypes, customers, permissions, sessions, tenant_only, users
[standard:public] Running migrations:
[standard:public]   Applying customers.0001_initial...
[standard:public]  OK
[standard:public]   Applying users.0001_initial...
[standard:public]  OK
[standard:public]   Applying contenttypes.0001_initial...
[standard:public]  OK
[standard:public]   Applying admin.0001_initial...
[standard:public]  OK
[standard:public]   Applying admin.0002_logentry_remove_auto_add...
[standard:public]  OK
[standard:public]   Applying admin.0003_logentry_add_action_flag_choices...
[standard:public]  OK
[standard:public]   Applying contenttypes.0002_remove_content_type_name...
[standard:public]  OK
[standard:public]   Applying auth.0001_initial...
[standard:public]  OK
[standard:public]   Applying auth.0002_alter_permission_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0003_alter_user_email_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0004_alter_user_username_opts...
[standard:public]  OK
[standard:public]   Applying auth.0005_alter_user_last_login_null...
[standard:public]  OK
[standard:public]   Applying auth.0006_require_contenttypes_0002...
[standard:public]  OK
[standard:public]   Applying auth.0007_alter_validators_add_error_messages...
[standard:public]  OK
[standard:public]   Applying auth.0008_alter_user_username_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0009_alter_user_last_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0010_alter_group_name_max_length...
[standard:public]  OK
[standard:public]   Applying auth.0011_update_proxy_permissions...
[standard:public]  OK
[standard:public]   Applying auth.0012_alter_user_first_name_max_length...
[standard:public]  OK
[standard:public]   Applying customers.0002_initial...
[standard:public]  OK
[standard:public]   Applying permissions.0001_initial...
[standard:public]  OK
[standard:public]   Applying sessions.0001_initial...
[standard:public]  OK
[standard:public]   Applying tenant_only.0001_initial...
[standard:public]  OK
------------------
check_schema_migrated
```

## Create the Public tenant and sample Tenant (EvilCorp)

```
❯ python manage.py shell     
Python 3.9.9 (main, Dec 13 2021, 16:26:26) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from tenant_users.tenants.utils import create_public_tenant
>>> create_public_tenant(domain_url="localhost", owner_email="admin@localhost")
------------------
check_post_schema_sync
(<Client: public>, <Domain: localhost>, <TenantUser: admin@localhost>)
>>> from tenant_users.tenants.tasks import provision_tenant
>>> fqdn = provision_tenant("EvilCorp", "evilcorp", "admin@localhost")
[1/1 (100%) standard:evilcorp_1706028118] === Starting migration
[1/1 (100%) standard:evilcorp_1706028118] Operations to perform:
[1/1 (100%) standard:evilcorp_1706028118]   Apply all migrations: admin, auth, contenttypes, customers, permissions, sessions, tenant_only, users
[1/1 (100%) standard:evilcorp_1706028118] Running migrations:
[1/1 (100%) standard:evilcorp_1706028118]   Applying customers.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying users.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying contenttypes.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying admin.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying admin.0002_logentry_remove_auto_add...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying admin.0003_logentry_add_action_flag_choices...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying contenttypes.0002_remove_content_type_name...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0002_alter_permission_name_max_length...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0003_alter_user_email_max_length...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0004_alter_user_username_opts...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0005_alter_user_last_login_null...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0006_require_contenttypes_0002...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0007_alter_validators_add_error_messages...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0008_alter_user_username_max_length...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0009_alter_user_last_name_max_length...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0010_alter_group_name_max_length...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0011_update_proxy_permissions...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying auth.0012_alter_user_first_name_max_length...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying customers.0002_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying permissions.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying sessions.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
[1/1 (100%) standard:evilcorp_1706028118]   Applying tenant_only.0001_initial...
[1/1 (100%) standard:evilcorp_1706028118]  OK
------------------
check_schema_migrated
------------------
check_post_schema_sync
```

## Run the Dev Server

```
❯ python manage.py runserver 8000
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 23, 2024 - 10:43:37
Django version 4.2.9, using settings 'tenant_tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

## Test!

I made two requests:
* `http://localhost:8000`
* `http://evilcorp.localhost:8000`

Both came up correctly, with the logs being:

```
[23/Jan/2024 10:43:45] "GET / HTTP/1.1" 200 2977
[23/Jan/2024 10:43:45] "GET /favicon.ico HTTP/1.1" 404 2226
[23/Jan/2024 10:43:51] "GET / HTTP/1.1" 200 2378
[23/Jan/2024 10:43:51] "GET /favicon.ico HTTP/1.1" 404 2634
```

Can you share specifics around where you're seeing issues? Command output, settings, etc., would be helpful in giving assistance.

**Comment by adnannazir** [comment]
Really sorry for any confusion. I mentioned that the django_plus_users is working fine but the one with the docker setup doesn't load the tenant view. (demo.localhost)
Honeslty, can't thank you enough for the time you spent in helping me. Many thanks for your efforts.

**Comment by Dresdn** [comment]
Gotcha. I took a quick look at the settings file, and the first thing I noticed was the [DATABASES setting](https://github.com/adnannazir/django_tenants_usage/blob/main/app/core/settings.py#L125-L134).

Take a look at the [django-tenants documentation](https://django-tenants.readthedocs.io/en/latest/) as only PostgreSQL is supported. Your settings are set to use SQLite, which doesn't support schemas.

**Comment by adnannazir** [comment]
> Gotcha. I took a quick look at the settings file, and the first thing I noticed was the [DATABASES setting](https://github.com/adnannazir/django_tenants_usage/blob/main/app/core/settings.py#L125-L134).
> 
> Take a look at the [django-tenants documentation](https://django-tenants.readthedocs.io/en/latest/) as only PostgreSQL is supported. Your settings are set to use SQLite, which doesn't support schemas.

Yes, that's just placeholder, the setting is coming from the .env.dev file 

DEBUG=1
SECRET_KEY=foo
DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
SQL_ENGINE=django_tenants.postgresql_backend
#django.db.backends.postgresql
SQL_DATABASE=my_little_user
SQL_USER=my_little_user
SQL_PASSWORD=my_little_user
SQL_HOST=db
SQL_PORT=5432
DATABASE=postgres

**Comment by Dresdn** [comment]
I took Docker out of the mix and just ran it setting local env vars. What specifically are you seeing?

Doing the same steps in my prior post, I see the following:

```
>>> from tenant_users.tenants.tasks import provision_tenant
>>> provision_tenant("EvilCorp", "evilcorp", "admin@localhost")
Traceback (most recent call last):
  File ".virtualenvs/django_tenants_usage-uulp/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "accounts_customer_code_key"
DETAIL:  Key (code)=() already exists.
```

This seems to be an issue with your [Customer model definition](https://github.com/adnannazir/django_tenants_usage/blob/main/app/accounts/models.py#L10-L12), specifically the `code` field. Since I don't see a management command, I'm assuming you're calling `provision_tenant()` the way I did, which doesn't include any extra values to set.

Your options seem to be:
1. Explicity set `code` so [it's unpacked during the `TenantModel.objects.create()` call](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/tasks.py#L98-L104): `provision_tenant("EvilCorp", "evilcorp", "admin@localhost", code="unique01")` **Note:** Same goes for the [`create_public_tenant()` call](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/utils.py#L77-L82), as `code` will be `''` for the Public Tenant.
2. Set a custom function as the default value of `code` like this:

```
import string
import secrets

def generate_code() -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for i in range(8))

class Customer(TenantBase):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, unique=True, default=generate_code)
```

**Comment by adnannazir** [comment]
> I took Docker out of the mix and just ran it setting local env vars. What specifically are you seeing?
> 
> Doing the same steps in my prior post, I see the following:
> 
> ```
> >>> from tenant_users.tenants.tasks import provision_tenant
> >>> provision_tenant("EvilCorp", "evilcorp", "admin@localhost")
> Traceback (most recent call last):
>   File ".virtualenvs/django_tenants_usage-uulp/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
>     return self.cursor.execute(sql, params)
> psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "accounts_customer_code_key"
> DETAIL:  Key (code)=() already exists.
> ```
> 
> This seems to be an issue with your [Customer model definition](https://github.com/adnannazir/django_tenants_usage/blob/main/app/accounts/models.py#L10-L12), specifically the `code` field. Since I don't see a management command, I'm assuming you're calling `provision_tenant()` the way I did, which doesn't include any extra values to set.
> 
> Your options seem to be:
> 
> 1. Explicity set `code` so [it's unpacked during the `TenantModel.objects.create()` call](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/tasks.py#L98-L104): `provision_tenant("EvilCorp", "evilcorp", "admin@localhost", code="unique01")` **Note:** Same goes for the [`create_public_tenant()` call](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/utils.py#L77-L82), as `code` will be `''` for the Public Tenant.
> 2. Set a custom function as the default value of `code` like this:
> 
> ```
> import string
> import secrets
> 
> def generate_code() -> str:
>     alphabet = string.ascii_letters + string.digits
>     return "".join(secrets.choice(alphabet) for i in range(8))
> 
> class Customer(TenantBase):
>     name = models.CharField(max_length=100)
>     code = models.CharField(max_length=50, unique=True, default=generate_code)
> ```



create_public_tenant(domain_url="localhost", owner_email="adnan@codevstan.com", tenant_extra_data={"code": "public"})

        self.stdout.write(self.style.SUCCESS('Default Tenant created successfully.'))

        User.objects.create_user("ad@codevstan.com", "A1234", True)

        provision_tenant("demo1", "demo", "ad@codevstan.com", tenant_extra_data={"code": "demo"})

**Comment by adnannazir** [comment]
> Side note, your [ALLOWED_HOSTS needs to be fixed to include subdomain wildcards](https://docs.djangoproject.com/en/5.0/ref/settings/#allowed-hosts), otherwise `foo.localhost` isn't going to with a setting of `localhost`.



Ok so first I must thank you that this actually solved my issue not .locahost but using * as in the example project of django_tenant
