### ISSUE TITLE
Example app is in previous version. An example in latest version is needed

### ISSUE THREAD

**Issue by Vineet-Sharma29** [Corvia/django-tenant-users#53]
It seems like current version of `dtu-test-project` is `1.8`.

I am unable to run the app with following version - `django-1.8`, `python-3.6` and `django-tenants-1.2.1`. I am able to run the server through `python manage.py runserver` command but unable to access any template at `localhost:8000/` and `localhost:8000/admin`.

Current `django` version is `3.0`. If the example app is in current version of django then it will be helpful.

**Comment by Viatrak** [comment]
Django 3 support issue already filed at https://github.com/Corvia/django-tenant-users/issues/40

PRs welcome.
