### ISSUE TITLE
Unable to pass the dictionary of password for the super user created with create_public_tenant

### ISSUE THREAD

**Issue by adnannazir** [Corvia/django-tenant-users#530]
**create_public_tenant(
    domain_url="localhost",
    owner_email="adnan@codevstan.com",
    tenant_extra_data={"code": "public"},
    owner_extra={ "password": "User"}
)**

throwing following error

Traceback (most recent call last):
demo_app-web-1  |   File "/usr/src/app/manage.py", line 22, in <module>
demo_app-web-1  |     main()
demo_app-web-1  |   File "/usr/src/app/manage.py", line 18, in main
demo_app-web-1  |     execute_from_command_line(sys.argv)
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
demo_app-web-1  |     utility.execute()
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
demo_app-web-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
demo_app-web-1  |     self.execute(*args, **cmd_options)
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
demo_app-web-1  |     output = self.handle(*args, **options)
demo_app-web-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
demo_app-web-1  |   File "/usr/src/app/accounts/management/commands/initialize_tenant.py", line 16, in handle
demo_app-web-1  |     create_public_tenant(domain_url="localhost", owner_email="adnan@codevstan.com",
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/tenant_users/tenants/utils.py", line 56, in create_public_tenant
demo_app-web-1  |     profile = UserModel.objects.create(
demo_app-web-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
demo_app-web-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
demo_app-web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 675, in create
demo_app-web-1  |     obj = self.model(**kwargs)
demo_app-web-1  |           ^^^^^^^^^^^^^^^^^^^^
demo_app-web-1  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
demo_app-web-1  |     raise TypeError(
demo_app-web-1  | TypeError: User() got unexpected keyword arguments: 'owner_extra'
demo_app-web-1  | Watching for file changes with StatReloader
demo_app-web-1  | Performing system checks...

**Comment by Dresdn** [comment]
For `create_public_tenant()`, [`owner_extra` isn't a parameter](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/utils.py#L22-L29), it's an unpacking operator on anything else (like `**kwargs` is).

Your usage should be:

```
create_public_tenant(
domain_url="localhost",
owner_email="adnan@codevstan.com",
tenant_extra_data={"code": "public"},
password="User"
)
```

**Comment by Dresdn** [comment]
To clarify, here's where it's unpacked: https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/utils.py#L56-L60

**Comment by adnannazir** [comment]
Many thanks for your fast feedback. Can't thank you enough.
