### ISSUE TITLE
What is the proper way to use the @login_required decorator with django-tenant-users?

### ISSUE THREAD

**Issue by adnannazir** [Corvia/django-tenant-users#534]
I am trying using login decorator to ensure only the authroized users access some views (of my tenant apps).
I have my accounts app in the SHARED_APPS list but its not being accessible in the tenant view. 

I have this in my project settings 
LOGIN_URL = 'accounts:login'

not able to understand that why the accounts app isn't being found?

![image](https://github.com/Corvia/django-tenant-users/assets/6734301/3cb37222-ca1b-460e-9c04-8eb5919304fe)

**Comment by adnannazir** [comment]
![image](https://github.com/Corvia/django-tenant-users/assets/6734301/58d10896-2173-4e4b-b96c-57d3b19c1269)


If my accounts/users apps is only in Shared apps then can that be accessible in my tenanted app?

**Comment by Dresdn** [comment]
To answer your question: yes. Shared apps are accessible in all tenant schemas.

The questions I would have are:
1. Are you using [PUBLIC_SCHEMA_URLCONF](https://django-tenants.readthedocs.io/en/latest/install.html#PUBLIC_SCHEMA_URLCONF)?
2. Does the `accounts` namespace exist for your URLs?

Seems like `django.urls.get_urlconf()` isn't finding `accounts`, so I'd check your `urls.py` config.

**Comment by adnannazir** [comment]
here is my urls_public.py

**Comment by adnannazir** [comment]
I mistakenly closed this question. 


here's my urls_public. py 

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]


here's my urls.py

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('scheduler.urls')),
    path('admin/', admin.site.urls),
]




ROOT_URLCONF = "core.urls"
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'
and this is my core.settings for urls

**Comment by Dresdn** [comment]
When browsing a non-public tenant, the `core.urls` is going to be used, and I don't see any `accounts` in that config. If you want the `accounts` namespace in both the Public and Tenant URLs, you'll need to ensure both URLCONF's know about it.

**Comment by adnannazir** [comment]
> When browsing a non-public tenant, the `core.urls` is going to be used, and I don't see any `accounts` in that config. If you want the `accounts` namespace in both the Public and Tenant URLs, you'll need to ensure both URLCONF's know about it.



Many thanks, that was my issue. I thought, the public_urls are always available and hence wasn't including it in the tenant urls file.
