### ISSUE TITLE
How to proceed with Django Tenants & Django Tenant Users for a Multi Level SAAS

### ISSUE THREAD

**Issue by adnannazir** [Corvia/django-tenant-users#539]
This is not an issue but a suggestion is required, I tried opening question at StackOverflow but didn't get any responses. 

I am making a multi level SAAS application where my client can have their own clients/departments. So If I am selling a service to a client, I am enabling them to use it for their department/ companies/ clients. 
I am using django-tenants and django-tenant-users where the super admin can create tenants, which is fine, but what if I need the data of this tenant along with the companies in the same schema? I mean, I will need to manage the tenancy of this level by myself. So a company X has the following departments IT, HR, Supply etc. The super admin of this tenant will create the departments and their data will be placed in the same schema and I will be required to check if a user has access to this department, only then the screens etc is allowed to be shown. This seems very inefficient to me as by this way, I will still need to manage all of this which I was trying to avoid by integrating some state of the art library like the django-tenant.

**Comment by Dresdn** [comment]
This isn't really related to this project as it's more of an application architecture question versus something specific to `django-tenant-users`.

That said, I'll offer my 2c. There's a lot that's not clear, but it seems like you want certain views to be accessible by a group. Just [define your groups](https://docs.djangoproject.com/en/5.0/topics/auth/default/#groups) and [define permissions on the view](https://docs.djangoproject.com/en/5.0/topics/auth/default/#the-permission-required-decorator), however you feel is appropriate.

Then you just let the tenant admin or whatever manage users' group memberships. Also, if you don't have users that need to switch schemas/companies, then I wouldn't even use `django-tenant-users` and stick with just `django-tenants` or some other type of data separation layout.
