### ISSUE TITLE
reverse accessor name clashes on groups and userpermission

### ISSUE THREAD

**Issue by rayvikram** [Corvia/django-tenant-users#54]
I am using django_tenants and tried to use this for user. But after following the steps mentioned- After runserver i am getting -

`File "/home/vikram/dev/ezeie/env/lib/python3.7/site-packages/django/core/management/base.py", line 436, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
permissions.UserTenantPermissions.groups: (fields.E304) Reverse accessor for 'UserTenantPermissions.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'UserTenantPermissions.groups' or 'User.groups'.
permissions.UserTenantPermissions.user_permissions: (fields.E304) Reverse accessor for 'UserTenantPermissions.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'UserTenantPermissions.user_permissions' or 'User.user_permissions'.
user.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'UserTenantPermissions.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'UserTenantPermissions.groups'.
user.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'UserTenantPermissions.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'UserTenantPermissions.user_permissions'.

System check identified 4 issues (0 silenced).
`

I am usingnDjango 2.2 with python 3.7.

**Comment by bouhaddiamine** [comment]
same problem

**Comment by vikramray-fc** [comment]
I end up not using this package.

**Comment by rayvikram** [comment]
I end up not using this package.

**Comment by bouhaddiamine** [comment]
@rayvikram any alternative ?

**Comment by rayvikram** [comment]
It was a long time ago, but i remember I end up implementing this on my own.

**Comment by bouhaddiamine** [comment]
do you remember how you did to have only one login page
