### ISSUE TITLE
Is UserProfile based on username or email address?

### ISSUE THREAD

**Issue by epschroeder** [Corvia/django-tenant-users#58]
Maybe a stupid question but I couldn't find this in the documentation.

I want to have users log in with their email address  and not a seperate username. Is UserProfile based on a username or email address?

Thanks,
Egbert

**Comment by sshahbaj** [comment]
The `USERNAME_FIELD` is set to `email` in [this](https://github.com/Corvia/django-tenant-users/blob/9f0569a648024ee7fa8ced7363987d68980bb74f/tenant_users/tenants/models.py#L304) line of code. Which means that UserProfile is based on email.
