### ISSUE TITLE
How to prevent tenants from seeing each others emails

### ISSUE THREAD

**Issue by Tekano985** [Corvia/django-tenant-users#61]
Hi, I'm using wagtail for my saas app but it seems all the tenant users appear in the wagtail users settings. Is there a way I can make each tenant to only view the users that relate to their tenants only?

**Comment by Viatrak** [comment]
There's no quick setting to flip for such a thing. Having the db schema-fall through to public on user lookup is fundamentally how this system works under the hood. You would have to write your own code/modify wagtail to make this possible.
