### ISSUE TITLE
Lots of SQL Queries

### ISSUE THREAD

**Issue by RuchitMicro** [Corvia/django-tenant-users#63]
This is a huge bottle neck to such an amazing plugin. The problem is that when I access my django admin there are atleast 400 SQL queries executed on every click and most of them being permission and user related stuff.
Please fix this issue, I have attached a screenshot of DjDt below.

![Screenshot from 2020-12-17 00-20-44](https://user-images.githubusercontent.com/29001411/102393345-3cd88d00-3ffe-11eb-976b-14d89786b0c6.png)

**Comment by sshahbaj** [comment]
Hey @RuchitMicro , please refer #25 . See if you can help out on this.
