### ISSUE TITLE
Value error when calling provision_tenant from tasks module

### ISSUE THREAD

**Issue by mugane-dj** [Corvia/django-tenant-users#676]
Got `ValueError` when calling `tasks.provision_tenant` in my django application when trying to access the tenant and domain instance after successful tenant migration.

## Expected Behavior
Tenant and domain instances should be returned as expected.

## Actual Behavior
Tenant and domain instances are inaccessible due to the following error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ValueError: too many values to unpack (expected 2)
```

## Steps to Reproduce
```
tenant, domain = tasks.provision_tenant(
     tenant_name="Foo",
     tenant_slug="foo",
     user_email="bar@mail.com",
     is_staff=True
)
```

## Your Environment
* Version used: 1.5.0
* Environment name and version: Django 5.0.7, pip 24.2
* Operating System and version: Ubuntu - 24.04.1

**Comment by Dresdn** [comment]
`1.5.0` doesn't contain the changes returning values from `tasks.provision_tenant()`. I'll get a release out today with that.
