### ISSUE TITLE
Project ownership / management

### ISSUE THREAD

**Issue by Dresdn** [Corvia/django-tenant-users#73]
Considering the age of multiple open issues and pull requests, do you have time @Viatrak to manage this project? I did see you ask in a PR if others wanted co-management privileges, and I'd be more than happy to help out.

I'm wanting to move to Django 3.2 as well as resolve a couple other issues, and it would be nice to have this in the official package. Otherwise, I'd be open to forking and start a new project if there is enough interest.

Thoughts?

**Comment by Dresdn** [comment]
@Viatrak - perhaps the project can join [Jazzband](https://jazzband.co/)? I'm more than happy to help out.

**Comment by Viatrak** [comment]
Contributions in the form of PRs or help on issues is strongly welcomed and encouraged. Most PRs eventually are merged.

Anyone is welcome to fork and develop.

As I had expressed in a PR, I am open to extending co-management privileges. Ideally the first order of business would be to develop a myriad of tests to mitigate regressions on further developments.

**Comment by Dresdn** [comment]
I do agree with that, and before doing tests, I think there needs to be proper tooling even.

I'll take a stab of setting up some tooling with poetry, tox, github actions, and do a test or two to show the syntax.

**Comment by Dresdn** [comment]
@Viatrak - Had some time to polish up the tooling, so I'll close this out.
