### ISSUE TITLE
Cross domain auth

### ISSUE THREAD

**Issue by ntbrown** [Corvia/django-tenant-users#9]
I'm completely new to tenant stuff, but your project seems like the exact solution I'm looking for (global users with authentication between multiple sites). However, all of the projects I see for this including django-tenants and this project seem to only allow subdomains from looking at the docs. 

Have I mistunderstood this or are domains allowed? My use case is that if a user logs into main-site.com they would need to be logged into site1.com, site2.com, .... so on and so forth. Similarly, I'm looking to share cookies, think a shopping cart, between the sites as well.

My project has tightly coupled code for the different sites, where each site points to a different app, and the urls are simply routed to the correct app based upon the domain.

Before I started monkeying around with this, and potentially wasting a massive amount of time, I was wondering if this is even possible using django-tenant-users?

Thank you.

**Comment by Viatrak** [comment]
This project works with django-tenant-schemas as well as django-tenants. Although I am only tangentially familiar with the latter, I'm under the impression it supports different domains mapped to tenants. See: https://github.com/tomturner/django-tenants/blob/fd1996e115072485c158988e591159c89f4ef42b/django_tenants/models.py#L171

However, I have not seen it used in the way you are describing so you are likely venturing into uncharted territory. Another option to explore is OAuth...
